version: '3.8'

networks:
  riotrank_network:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      riotrank_network:
        ipv4_address: 10.0.0.2
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev
    networks:
      riotrank_network:
        ipv4_address: 10.0.0.3
volumes:
  postgres_data:
