# Generated by Django 4.2.6 on 2023-10-23 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(default=1, max_length=18, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('team_code', models.CharField(blank=True, default='', max_length=100)),
                ('team_name', models.CharField(blank=True, default='', max_length=100)),
                ('rank', models.IntegerField(default=777)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.CharField(default=1, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('tournament_name', models.CharField(blank=True, default='', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=1, max_length=18, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.team')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentRanking',
            fields=[
                ('tournament_ranking_id', models.CharField(default=1, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('stage', models.CharField(blank=True, default='', max_length=100)),
                ('tournament_rank', models.IntegerField(default=777)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.team')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TeamRanking',
            fields=[
                ('team_ranking_id', models.CharField(default=1, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('tournament_rank', models.IntegerField(default=777)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.team')),
                ('tournament_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.CharField(default=1, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.team')),
            ],
        ),
    ]
