# Generated by Django 4.2.6 on 2023-10-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_team_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
